apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-configmap
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: webapp-namespace
data:
  hello: This is a hello message returned from the ConfigMap
