apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-mysql
  namespace: webapp-namespace
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: release1
    meta.helm.sh/release-namespace: webapp-namespace
spec:
  selector:
    matchLabels:
      app: webapp-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webapp-mysql
    spec:
      containers:
      - image: mysql:5.6
        name: webapp-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: database
        ports:
        - containerPort: 3306
          name: webapp-mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-backend
  namespace: webapp-namespace
  labels:
    app: webapp-deployment-backend
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: release1
    meta.helm.sh/release-namespace: webapp-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-backend
  template:
    metadata:
      labels:
        app: webapp-backend
    spec:
      containers:
      - name: webapp-backend
        image: paulagiurgiu/backend-webapp:latest
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: database
        - name: HELLO
          valueFrom:
            configMapKeyRef:
              name: webapp-configmap
              key: hello
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-frontend
  namespace: webapp-namespace
  labels:
    app: webapp-frontend
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: release1
    meta.helm.sh/release-namespace: webapp-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-frontend
  template:
    metadata:
      labels:
        app: webapp-frontend
    spec:
      containers:
      - name: webapp-frontend
        image: paulagiurgiu/frontend-webapp-paula:latest
        ports:
        - containerPort: 3000
