apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: webapp-namespace
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: release1
    meta.helm.sh/release-namespace: webapp-namespace
type: kubernetes.io/basic-auth
stringData:
  password: test1234
  database: db
