apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: webapp-namespace
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: release1
    meta.helm.sh/release-namespace: webapp-namespace
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: webapp-mysql

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-backend-service
  namespace: webapp-namespace
  labels:
    app: webapp-backend
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: release1
    meta.helm.sh/release-namespace: webapp-namespace
spec:
  selector:
    app: webapp-backend
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-frontend-service
  namespace: webapp-namespace
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: release1
    meta.helm.sh/release-namespace: webapp-namespace
spec:
  selector:
    app: webapp-frontend
  ports:
    - port: 3000
